package ir.promptall.app.data

import android.content.Context
import android.net.Uri

/**
 * Lightweight compatibility layer for the normal image-search request.
 *
 * The PromptAll search backend ranks the current mobile/web search using the
 * perceptual fingerprints generated by [ImageFingerprint] (pHash/dHash/aHash
 * + histogram). Local ML Kit labels were previously sent as optional metadata,
 * but they are not required for the current backend matcher and pulled a large
 * native runtime into the APK.
 *
 * Keeping this API means the search flow remains source-compatible while the
 * release APK stays small. Semantic matching is still available through the
 * explicit Gemini fallback selected by the user.
 */
data class LocalImageLabel(
    val text: String,
    val confidence: Double,
)

object ImageLabelAnalyzer {
    @Suppress("UNUSED_PARAMETER")
    suspend fun fromUri(context: Context, uri: Uri): List<LocalImageLabel> = emptyList()
}
